// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'music/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `global_playback_session`, `open_scan_conn`, `open_stats_conn`, `parse_remote_source`

/// 解析原始歌词文本（LRC/YRC/QRC/ESLRC/TTML/Lys 等），
/// 返回 [`StructuredLyricsPayload`] 的 JSON（camelCase）。
///
/// 包含 `document`（解析出的多轨结构）、`semanticLines`（语义行）和
/// `displayLines`（可直接用于逐行/逐字播放的展示行，含 translation/romaji）。
/// 解析失败或空文本时返回合法 JSON 结构而非错误。
Future<String> parseLyrics({required String rawLyrics}) =>
    RustLib.instance.api.crateApiParseLyrics(rawLyrics: rawLyrics);

/// 解析 LX 音源播放直链。
///
/// - `song_info_json`：[`LxUrlSongInfo`] 的 JSON（camelCase）
/// - `quality`：音质（如 "128k"、"320k"、"flac" 等）
///
/// 返回 [`ResolvedUrl`] 的 JSON；解析失败返回 `"null"`。
Future<String> lxResolveUrl({
  required String songInfoJson,
  required String quality,
  String? dataDir,
}) => RustLib.instance.api.crateApiLxResolveUrl(
  songInfoJson: songInfoJson,
  quality: quality,
  dataDir: dataDir,
);

/// 搜索音乐源。`source` ∈ `kw`/`kg`/`tx`/`wy`/`mg`。
/// 返回 [`LxSearchItem`] 数组的 JSON；失败返回错误信息。
Future<String> lxSearch({
  required String source,
  required String keyword,
  required int limit,
}) => RustLib.instance.api.crateApiLxSearch(
  source: source,
  keyword: keyword,
  limit: limit,
);

/// 列出已安装的音源插件（返回 `PluginInfo[]` JSON）。
Future<String> pluginList({required String dataDir}) =>
    RustLib.instance.api.crateApiPluginList(dataDir: dataDir);

/// 从脚本文本安装音源插件。
///
/// 安装前会在 QuickJS 引擎中试运行，脚本无效时直接返回错误。
/// 返回安装后的 `PluginInfo` JSON。
Future<String> pluginInstallScript({
  required String dataDir,
  required String script,
  required String origin,
}) => RustLib.instance.api.crateApiPluginInstallScript(
  dataDir: dataDir,
  script: script,
  origin: origin,
);

/// 从本地文件安装音源插件（限 `.js`）。
Future<String> pluginInstallFile({
  required String dataDir,
  required String path,
}) => RustLib.instance.api.crateApiPluginInstallFile(
  dataDir: dataDir,
  path: path,
);

/// 从订阅 URL 安装音源插件。
Future<String> pluginInstallUrl({
  required String dataDir,
  required String url,
}) => RustLib.instance.api.crateApiPluginInstallUrl(dataDir: dataDir, url: url);

/// 启用或停用插件。
Future<void> pluginSetEnabled({
  required String dataDir,
  required String id,
  required bool enabled,
}) => RustLib.instance.api.crateApiPluginSetEnabled(
  dataDir: dataDir,
  id: id,
  enabled: enabled,
);

/// 卸载插件。
Future<void> pluginRemove({required String dataDir, required String id}) =>
    RustLib.instance.api.crateApiPluginRemove(dataDir: dataDir, id: id);

/// 从指定音源抓取歌词（kg/kw/tx/wy）。
///
/// - `song_info_json`：[
/// `LyricSongInfo`] 的 JSON（camelCase）
///
/// 返回 [`LyricResult`]（含 lyric/tlyric/rlyric/lxlyric）的 JSON；
/// 该音源无歌词返回 `"null"`。
Future<String> fetchLyricFromSource({
  required String source,
  required String songInfoJson,
}) => RustLib.instance.api.crateApiFetchLyricFromSource(
  source: source,
  songInfoJson: songInfoJson,
);

/// 测试 WebDAV 连接（列出根目录）。
Future<void> webdavTestConnection({required String sourceJson}) =>
    RustLib.instance.api.crateApiWebdavTestConnection(sourceJson: sourceJson);

/// 按已保存远程源测试连接：读取存储凭证（含密码），叠加表单覆盖项后 PROPFIND 根目录。
///
/// 用于编辑场景：密码输入框留空表示沿用原密码，仅测试连接无需先保存。
Future<void> webdavTestSavedSource({
  required String dbPath,
  required String sourceId,
  required String overridesJson,
}) => RustLib.instance.api.crateApiWebdavTestSavedSource(
  dbPath: dbPath,
  sourceId: sourceId,
  overridesJson: overridesJson,
);

/// 播放前直接读取文件 ReplayGain 标签并计算 Linear Gain（无 DB 缓存）。
///
/// 无标签 / 读取失败返回 1.0（原始音量播放）。
Future<double> loudnessPlaybackGainForFile({
  required String filePath,
  required double gainOffsetDb,
  required bool preventClipping,
}) => RustLib.instance.api.crateApiLoudnessPlaybackGainForFile(
  filePath: filePath,
  gainOffsetDb: gainOffsetDb,
  preventClipping: preventClipping,
);

/// 记录一次播放事件（含聚合统计与播放历史）。
///
/// - `db_path`：SQLite 数据库文件路径
/// - `payload_json`：[`RecordPlayPayload`] 的 JSON（camelCase，如
///   `{"songPath":"...","listenedMs":30000,"durationMs":195000,"title":"...","artist":"..."}`）
Future<void> statsRecordPlay({
  required String dbPath,
  required String payloadJson,
}) => RustLib.instance.api.crateApiStatsRecordPlay(
  dbPath: dbPath,
  payloadJson: payloadJson,
);

/// 获取三个周期的听歌时长（日/周/总），返回 JSON 秒数。
Future<String> statsGetListenDurations({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsGetListenDurations(dbPath: dbPath);

/// 获取行为统计（Top 歌曲/歌手/专辑、时段分布、近期活跃）。
///
/// - `time_range_json`：[`TimeRange`] 的 JSON（如 `{"type":"Days30"}`）
Future<String> statsGetBehaviorStats({
  required String dbPath,
  required String timeRangeJson,
}) => RustLib.instance.api.crateApiStatsGetBehaviorStats(
  dbPath: dbPath,
  timeRangeJson: timeRangeJson,
);

/// 获取最近播放历史（去重，按播放时间倒序）。
Future<String> statsGetRecentHistory({required String dbPath, BigInt? limit}) =>
    RustLib.instance.api.crateApiStatsGetRecentHistory(
      dbPath: dbPath,
      limit: limit,
    );

/// 添加一条最近播放记录。
Future<void> statsAddToHistory({
  required String dbPath,
  required String songPath,
}) => RustLib.instance.api.crateApiStatsAddToHistory(
  dbPath: dbPath,
  songPath: songPath,
);

/// 清空最近播放历史。
Future<void> statsClearRecentHistory({required String dbPath}) =>
    RustLib.instance.api.crateApiStatsClearRecentHistory(dbPath: dbPath);

/// 从最近播放历史移除指定歌曲。
Future<void> statsRemoveFromRecentHistory({
  required String dbPath,
  required List<String> songPaths,
}) => RustLib.instance.api.crateApiStatsRemoveFromRecentHistory(
  dbPath: dbPath,
  songPaths: songPaths,
);

/// 导出统计备份到 JSON 文件。
///
/// - `options_json`：[`StatisticsExportOptions`] 的 JSON（camelCase，含 `filePath`/`includeRecentPlays`）
Future<String> statsExportStatisticsFile({
  required String dbPath,
  required String optionsJson,
}) => RustLib.instance.api.crateApiStatsExportStatisticsFile(
  dbPath: dbPath,
  optionsJson: optionsJson,
);

/// 预览统计备份导入（不写库）。
Future<String> statsPreviewStatisticsImport({
  required String dbPath,
  required String optionsJson,
}) => RustLib.instance.api.crateApiStatsPreviewStatisticsImport(
  dbPath: dbPath,
  optionsJson: optionsJson,
);

/// 导入统计备份。
///
/// - `options_json`：[`StatisticsImportOptions`] 的 JSON（camelCase，
///   含 `filePath`/`mode`("overwrite"|"merge")/`continueDuplicateImport`）
Future<String> statsImportStatisticsFile({
  required String dbPath,
  required String optionsJson,
}) => RustLib.instance.api.crateApiStatsImportStatisticsFile(
  dbPath: dbPath,
  optionsJson: optionsJson,
);

/// 增量扫描一个音乐文件夹，将新增/更新/删除写入数据库，返回该文件夹全部歌曲 JSON。
///
/// - `db_path`：SQLite 数据库文件路径
/// - `folder_path`：要扫描的文件夹路径
/// - `minimum_duration_seconds`：低于该时长的歌曲被过滤（0 表示不过滤）
Future<String> scanMusicFolder({
  required String dbPath,
  required String folderPath,
  int? minimumDurationSeconds,
  List<String>? allowedFormats,
}) => RustLib.instance.api.crateApiScanMusicFolder(
  dbPath: dbPath,
  folderPath: folderPath,
  minimumDurationSeconds: minimumDurationSeconds,
  allowedFormats: allowedFormats,
);

/// Android SAF：从一个已被 Android 侧通过 ContentResolver 打开的 fd 解析单个音频，
/// 返回曲库 [`Song`] JSON。读取走 `/proc/self/fd/<fd>`，解析逻辑与路径扫描完全一致。
Future<String> parseAudioFromFdAndroid({
  required int fd,
  required String fileName,
  required String pathKey,
  required String format,
}) => RustLib.instance.api.crateApiParseAudioFromFdAndroid(
  fd: fd,
  fileName: fileName,
  pathKey: pathKey,
  format: format,
);

/// Android SAF：把一批已解析歌曲增量提交到 `folder_key`（SAF tree documentId）名下。
/// 复用桌面同款增量 diff，保证新增/变更/删除在库内一致。
Future<String> scanSafSongsCommit({
  required String dbPath,
  required String folderKey,
  required String songsJson,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiScanSafSongsCommit(
  dbPath: dbPath,
  folderKey: folderKey,
  songsJson: songsJson,
  minimumDurationSeconds: minimumDurationSeconds,
);

/// 列出全部远程源（返回 [`RemoteSource`] 数组 JSON）。
Future<String> listRemoteSources({required String dbPath}) =>
    RustLib.instance.api.crateApiListRemoteSources(dbPath: dbPath);

/// 新增或更新远程源（按 `RemoteSourceInput` JSON，缺 id 则新增）。
Future<String> saveRemoteSource({
  required String dbPath,
  required String sourceJson,
}) => RustLib.instance.api.crateApiSaveRemoteSource(
  dbPath: dbPath,
  sourceJson: sourceJson,
);

/// 删除远程源及其关联歌曲。
Future<void> removeRemoteSource({
  required String dbPath,
  required String sourceId,
}) => RustLib.instance.api.crateApiRemoveRemoteSource(
  dbPath: dbPath,
  sourceId: sourceId,
);

/// 同步远程源：扫描远程目录、增量解析并写入音乐库。
///
/// - `cache_root`：远程音频缓存根目录（调用方传入 app 缓存目录）
/// - `source_id`：远程源 id
///
/// 返回 [`RemoteSyncResult`] JSON。
Future<String> syncRemoteSource({
  required String dbPath,
  required String cacheRoot,
  required String sourceId,
}) => RustLib.instance.api.crateApiSyncRemoteSource(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  sourceId: sourceId,
);

/// 查询远程音频缓存占用（返回 [`RemoteCacheUsage`] JSON）。
Future<String> getRemoteCacheUsage({required String cacheRoot}) =>
    RustLib.instance.api.crateApiGetRemoteCacheUsage(cacheRoot: cacheRoot);

/// 清空远程音频缓存（返回清空后 [`RemoteCacheUsage`] JSON）。
Future<String> clearRemoteCache({required String cacheRoot}) =>
    RustLib.instance.api.crateApiClearRemoteCache(cacheRoot: cacheRoot);

/// 解析远程音乐播放来源：已缓存返回本地路径，未缓存返回直链流。
///
/// 返回 `{"kind":"cached","path":...}` 或 `{"kind":"stream","url":...,...}` JSON。
Future<String> remotePlaybackSource({
  required String dbPath,
  required String remoteUri,
}) => RustLib.instance.api.crateApiRemotePlaybackSource(
  dbPath: dbPath,
  remoteUri: remoteUri,
);

/// 向账号 API 发起带签名的 POST 请求（返回响应 JSON）。
Future<String> authAuthedRequest({
  required String dataDir,
  required String action,
  required String bodyJson,
  BigInt? fetchTimeoutMs,
}) => RustLib.instance.api.crateApiAuthAuthedRequest(
  dataDir: dataDir,
  action: action,
  bodyJson: bodyJson,
  fetchTimeoutMs: fetchTimeoutMs,
);

/// 保存认证凭证（token + user JSON 写入 auth 目录）。
Future<void> authSaveCredentials({
  required String dataDir,
  required String token,
  required String userJson,
}) => RustLib.instance.api.crateApiAuthSaveCredentials(
  dataDir: dataDir,
  token: token,
  userJson: userJson,
);

/// 读取认证凭证（返回 `AuthCredentials` JSON 或 null）。
Future<String> authGetCredentials({required String dataDir}) =>
    RustLib.instance.api.crateApiAuthGetCredentials(dataDir: dataDir);

/// 清除认证凭证。
Future<void> authClearCredentials({required String dataDir}) =>
    RustLib.instance.api.crateApiAuthClearCredentials(dataDir: dataDir);

/// 设置 API 基地址。
Future<void> authSetBaseUrl({
  required String dataDir,
  required String baseUrl,
}) => RustLib.instance.api.crateApiAuthSetBaseUrl(
  dataDir: dataDir,
  baseUrl: baseUrl,
);

/// 设置 API 签名密钥。
Future<void> authSetApiSecret({
  required String dataDir,
  required String apiSecret,
}) => RustLib.instance.api.crateApiAuthSetApiSecret(
  dataDir: dataDir,
  apiSecret: apiSecret,
);

/// 读取音乐库文件夹（返回 `LibraryFolder[]` JSON，含歌曲数）。
Future<String> getLibraryFolders({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryFolders(dbPath: dbPath);

/// 新增音乐库文件夹。
Future<void> addLibraryFolder({required String dbPath, required String path}) =>
    RustLib.instance.api.crateApiAddLibraryFolder(dbPath: dbPath, path: path);

/// 移除音乐库文件夹及其后代歌曲。
Future<void> removeLibraryFolder({
  required String dbPath,
  required String path,
}) => RustLib.instance.api.crateApiRemoveLibraryFolder(
  dbPath: dbPath,
  path: path,
);

/// 读取全部本地曲库歌曲（返回 `LibrarySong[]` JSON）。
Future<String> getLibrarySongsCached({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibrarySongsCached(dbPath: dbPath);

/// 按路径批量查询歌曲（返回 `LibrarySong[]` JSON）。
Future<String> getLibrarySongsByPaths({
  required String dbPath,
  required List<String> paths,
}) => RustLib.instance.api.crateApiGetLibrarySongsByPaths(
  dbPath: dbPath,
  paths: paths,
);

/// 搜索本地音乐库（返回 `LibrarySong[]` JSON）。
Future<String> searchLibrarySongs({
  required String dbPath,
  required String query,
  BigInt? limit,
}) => RustLib.instance.api.crateApiSearchLibrarySongs(
  dbPath: dbPath,
  query: query,
  limit: limit,
);

/// 读取歌手目录（返回 `ArtistCatalogItem[]` JSON）。
Future<String> getLibraryArtistCatalog({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryArtistCatalog(dbPath: dbPath);

/// 读取专辑目录（返回 `AlbumCatalogItem[]` JSON）。
Future<String> getLibraryAlbumCatalog({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryAlbumCatalog(dbPath: dbPath);

/// 按歌手名获取歌曲路径列表。
Future<String> getLibrarySongPathsByArtist({
  required String dbPath,
  required String artistName,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsByArtist(
  dbPath: dbPath,
  artistName: artistName,
);

/// 按专辑 key 获取歌曲路径列表。
Future<String> getLibrarySongPathsByAlbum({
  required String dbPath,
  required String albumKey,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsByAlbum(
  dbPath: dbPath,
  albumKey: albumKey,
);

/// 文件夹视图的歌曲路径列表（支持查询过滤与排序）。
///
/// - `sort_mode`：`"title"`/`"name"`/`"artist"`/`"addedAt"`/`"addedAtAsc"`/`"trackNumber"`
Future<String> getLibrarySongPathsForFolderView({
  required String dbPath,
  required String folderPath,
  String? query,
  required String sortMode,
}) => RustLib.instance.api.crateApiGetLibrarySongPathsForFolderView(
  dbPath: dbPath,
  folderPath: folderPath,
  query: query,
  sortMode: sortMode,
);

/// 递归构建音乐库文件夹目录树（返回 `FolderNode[]` JSON）。
Future<String> getLibraryHierarchy({required String dbPath}) =>
    RustLib.instance.api.crateApiGetLibraryHierarchy(dbPath: dbPath);

/// 获取歌曲缩略图封面（远程 URI 先缓存到本地），返回缓存路径字符串。
Future<String> getSongCoverThumbnail({
  required String dbPath,
  required String cacheRoot,
  required String path,
}) => RustLib.instance.api.crateApiGetSongCoverThumbnail(
  dbPath: dbPath,
  cacheRoot: cacheRoot,
  path: path,
);

/// 读取并解析歌曲歌词（返回 `StructuredLyricsPayload` JSON）。
Future<String> getSongLyricsPayload({
  required String dbPath,
  required String path,
}) => RustLib.instance.api.crateApiGetSongLyricsPayload(
  dbPath: dbPath,
  path: path,
);

/// 读取歌曲歌词用于编辑（返回 `SongLyricsForEdit` JSON）。
Future<String> getSongLyricsForEdit({required String path}) =>
    RustLib.instance.api.crateApiGetSongLyricsForEdit(path: path);

/// 保存歌曲歌词（内嵌或侧边 LRC），返回 `SongLyricsForEdit` JSON。
Future<String> saveSongLyrics({
  required String path,
  required String lyrics,
  required LyricsStorageSource source,
  String? sourcePath,
}) => RustLib.instance.api.crateApiSaveSongLyrics(
  path: path,
  lyrics: lyrics,
  source: source,
  sourcePath: sourcePath,
);

/// 保存歌曲信息标签（返回 `SaveSongInfoResponse` JSON）。
Future<String> saveSongInfo({
  required String dbPath,
  required String path,
  required String payloadJson,
}) => RustLib.instance.api.crateApiSaveSongInfo(
  dbPath: dbPath,
  path: path,
  payloadJson: payloadJson,
);

/// 读取歌曲详情（返回 `SongDetail` JSON）。
Future<String> getSongDetail({required String dbPath, required String path}) =>
    RustLib.instance.api.crateApiGetSongDetail(dbPath: dbPath, path: path);

/// 保存完整播放会话状态（写入内存 + SQLite）。
Future<void> savePlaybackSession({
  required String dbPath,
  required String sessionJson,
}) => RustLib.instance.api.crateApiSavePlaybackSession(
  dbPath: dbPath,
  sessionJson: sessionJson,
);

/// 从 SQLite 加载播放会话到内存，返回 `PlaybackSessionData` JSON。
Future<String> loadPlaybackSession({required String dbPath}) =>
    RustLib.instance.api.crateApiLoadPlaybackSession(dbPath: dbPath);

/// 高频更新播放进度（防抖写 SQLite）。
Future<void> updatePlaybackPosition({
  required String dbPath,
  required double positionSecs,
  required bool isPlaying,
}) => RustLib.instance.api.crateApiUpdatePlaybackPosition(
  dbPath: dbPath,
  positionSecs: positionSecs,
  isPlaying: isPlaying,
);

/// 预览批量重命名（返回 `RenamePreview[]` JSON）。
///
/// - `config_json`：[`RenameConfig`] 的 JSON（camelCase，含 `mode`/`template`/
///   `removeTrackPrefix`/`removeSourcePrefix`）
Future<String> previewRename({
  required String rootPath,
  required String configJson,
}) => RustLib.instance.api.crateApiPreviewRename(
  rootPath: rootPath,
  configJson: configJson,
);

/// 执行批量重命名（返回成功数）。
///
/// - `operations_json`：[`RenameOperation`] 数组的 JSON（camelCase，含 `originalPath`/`newName`）
Future<int> applyRename({required String operationsJson}) =>
    RustLib.instance.api.crateApiApplyRename(operationsJson: operationsJson);

/// 刷新指定文件夹歌曲（增量扫描并写库，返回该文件夹全部歌曲 JSON）。
Future<String> refreshFolderSongs({
  required String dbPath,
  required String folderPath,
  int? minimumDurationSeconds,
}) => RustLib.instance.api.crateApiRefreshFolderSongs(
  dbPath: dbPath,
  folderPath: folderPath,
  minimumDurationSeconds: minimumDurationSeconds,
);

/// 根据歌曲信息构建下载文件名并解析非冲突完整路径（单次调用）。
Future<String> resolveDownloadFullPath({
  required String directory,
  required String title,
  required String artist,
  required String album,
  required String url,
  required String quality,
  required bool keepSourceFilename,
  required String fileNameStyle,
  required bool overwriteExisting,
}) => RustLib.instance.api.crateApiResolveDownloadFullPath(
  directory: directory,
  title: title,
  artist: artist,
  album: album,
  url: url,
  quality: quality,
  keepSourceFilename: keepSourceFilename,
  fileNameStyle: fileNameStyle,
  overwriteExisting: overwriteExisting,
);

/// 启动 USB 独占播放。返回设备名或错误信息。
/// `device_id` = AAudio 设备 ID（USB DAC），-1 = 默认设备。
Future<String> startUsbExclusivePlayback({
  required String path,
  required int deviceId,
  required double volume,
  required double startTimeSecs,
  required bool isPlaying,
  required double volumeBalanceGain,
  required String equalizerSettingsJson,
  required String soundEffectSettingsJson,
}) => RustLib.instance.api.crateApiStartUsbExclusivePlayback(
  path: path,
  deviceId: deviceId,
  volume: volume,
  startTimeSecs: startTimeSecs,
  isPlaying: isPlaying,
  volumeBalanceGain: volumeBalanceGain,
  equalizerSettingsJson: equalizerSettingsJson,
  soundEffectSettingsJson: soundEffectSettingsJson,
);

/// 停止 USB 独占播放并释放设备。
Future<void> stopUsbExclusivePlayback() =>
    RustLib.instance.api.crateApiStopUsbExclusivePlayback();

/// 跳转到指定位置（秒）。
Future<void> seekUsbExclusive({
  required double timeSecs,
  required bool isPlaying,
}) => RustLib.instance.api.crateApiSeekUsbExclusive(
  timeSecs: timeSecs,
  isPlaying: isPlaying,
);

/// 设置用户音量（0.0–1.0）。
Future<void> setUsbExclusiveVolume({required double volume}) =>
    RustLib.instance.api.crateApiSetUsbExclusiveVolume(volume: volume);

/// 运行时更新独占管线的音量平衡（ReplayGain）目标增益（平滑渐变不断音）。
Future<void> setUsbExclusiveVolumeBalanceGain({required double gain}) =>
    RustLib.instance.api.crateApiSetUsbExclusiveVolumeBalanceGain(gain: gain);

/// 更新 EQ 设置（camelCase JSON）。
Future<void> setUsbExclusiveEqualizer({required String settingsJson}) => RustLib
    .instance
    .api
    .crateApiSetUsbExclusiveEqualizer(settingsJson: settingsJson);

/// 更新音效设置（camelCase JSON）。
Future<void> setUsbExclusiveSoundEffect({required String settingsJson}) =>
    RustLib.instance.api.crateApiSetUsbExclusiveSoundEffect(
      settingsJson: settingsJson,
    );

/// 获取当前播放位置（秒）。
Future<double> getUsbExclusivePositionSecs() =>
    RustLib.instance.api.crateApiGetUsbExclusivePositionSecs();

/// 下载在线歌曲真实音源直链到指定路径（流式写入 + QMC2 解密），返回最终路径。
///
/// - `headers_json`：可选 HTTP 头 JSON（对象）
/// - `ekey`：可选 QMC2 加密 key（base64）
Future<String> downloadOnlineSong({
  required String url,
  required String destPath,
  String? ekey,
  required String headersJson,
}) => RustLib.instance.api.crateApiDownloadOnlineSong(
  url: url,
  destPath: destPath,
  ekey: ekey,
  headersJson: headersJson,
);

/// 独立解密 QMC 加密文件（用户手动选择文件的工具入口）。
///
/// 支持三档策略：ekey 直供 / footer 自动提取 → QMC2；QMC1 老格式扩展名 → 固定密钥解密。
/// 解密成功后按内容修正扩展名。返回 JSON
/// `{"status":"decrypted"|"not_encrypted","outputPath":...,"renamedTo":...,"crypto":...}`。
Future<String> decryptQmcFileStandalone({
  required String filePath,
  String? ekey,
}) => RustLib.instance.api.crateApiDecryptQmcFileStandalone(
  filePath: filePath,
  ekey: ekey,
);

/// 下载后收尾编排：歌词保存 + 封面下载保存 + 元数据嵌入。
///
/// - `request_json`：[`FinalizeDownloadExtrasRequest`] 的 JSON（camelCase）
///
/// 返回 [`FinalizeDownloadExtrasResult`] JSON（camelCase）。
Future<String> finalizeDownloadExtras({required String requestJson}) => RustLib
    .instance
    .api
    .crateApiFinalizeDownloadExtras(requestJson: requestJson);

/// 读取下载记录 JSON 文本（文件不存在或损坏时返回 `"{}"`）。
Future<String> readDownloadHistory({required String dataDir}) =>
    RustLib.instance.api.crateApiReadDownloadHistory(dataDir: dataDir);

/// 写入下载记录 JSON 文本（整体覆盖，自动创建父目录）。
Future<void> writeDownloadHistory({
  required String dataDir,
  required String content,
}) => RustLib.instance.api.crateApiWriteDownloadHistory(
  dataDir: dataDir,
  content: content,
);

/// 获取公告（返回解析出的 data JSON 字符串）。
Future<String> fetchAnnouncement() =>
    RustLib.instance.api.crateApiFetchAnnouncement();

/// 读取插件/文本文件内容（限 `.js/.json/.txt/.m3u/.m3u8`）。
Future<String> readPluginFile({required String path}) =>
    RustLib.instance.api.crateApiReadPluginFile(path: path);

/// 代理图片请求（自动添加 Referer，返回 data URL）。
Future<String> proxyImage({required String url, String? referer}) =>
    RustLib.instance.api.crateApiProxyImage(url: url, referer: referer);

/// 初始化全局插件引擎（首次调用时以 `data_dir` 建立 Cookie/Storage 存储）。
Future<void> pluginEngineInit({required String dataDir}) =>
    RustLib.instance.api.crateApiPluginEngineInit(dataDir: dataDir);

/// 加载 LX 格式插件，返回 `EngineLoadResult` JSON（`ok`/`error`/`metadata`/`logs`）。
Future<String> pluginEngineLoadLx({
  required String dataDir,
  required String pluginId,
  required String script,
  required String scriptInfoJson,
}) => RustLib.instance.api.crateApiPluginEngineLoadLx(
  dataDir: dataDir,
  pluginId: pluginId,
  script: script,
  scriptInfoJson: scriptInfoJson,
);

/// 加载 MusicFree 格式插件，返回 `EngineLoadResult` JSON。
Future<String> pluginEngineLoadMusicfree({
  required String dataDir,
  required String pluginId,
  required String script,
  required String userVarsJson,
}) => RustLib.instance.api.crateApiPluginEngineLoadMusicfree(
  dataDir: dataDir,
  pluginId: pluginId,
  script: script,
  userVarsJson: userVarsJson,
);

/// 调用插件方法，返回 `EngineCallResult` JSON（`ok`/`error`/`data`/`logs`）。
Future<String> pluginEngineCall({
  required String dataDir,
  required String pluginId,
  required String method,
  required String argsJson,
  String? userVarsJson,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiPluginEngineCall(
  dataDir: dataDir,
  pluginId: pluginId,
  method: method,
  argsJson: argsJson,
  userVarsJson: userVarsJson,
  timeoutMs: timeoutMs,
);

/// 销毁指定插件的沙箱实例。
Future<void> pluginEngineDestroy({
  required String dataDir,
  required String pluginId,
}) => RustLib.instance.api.crateApiPluginEngineDestroy(
  dataDir: dataDir,
  pluginId: pluginId,
);

/// 销毁全部插件沙箱实例。
Future<void> pluginEngineDestroyAll({required String dataDir}) =>
    RustLib.instance.api.crateApiPluginEngineDestroyAll(dataDir: dataDir);

/// 取消正在进行的音频识别。
Future<void> cancelRecognizeSystemAudio() =>
    RustLib.instance.api.crateApiCancelRecognizeSystemAudio();

/// 使用自定义 PCM 数据识别歌曲（8000Hz/16bit/单声道），返回 `RecognizeResponse` JSON。
Future<String> recognizeWithPcm({required List<int> pcm}) =>
    RustLib.instance.api.crateApiRecognizeWithPcm(pcm: pcm);

/// 已保存远程源的表单覆盖项（编辑时密码留空则沿用存储密码）。
class WebdavSourceOverrides {
  final String? baseUrl;
  final String? username;
  final String? rootPath;

  const WebdavSourceOverrides({this.baseUrl, this.username, this.rootPath});

  static Future<WebdavSourceOverrides> default_() =>
      RustLib.instance.api.crateApiWebdavSourceOverridesDefault();

  @override
  int get hashCode => baseUrl.hashCode ^ username.hashCode ^ rootPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebdavSourceOverrides &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          username == other.username &&
          rootPath == other.rootPath;
}
